/**
 * Flowtype definitions for index
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.11.0
 */

import { CSSProperties, DOMAttributes } from "react";
import {
  Transform,
  IconProp,
  FlipProp,
  SizeProp,
  PullProp,
  RotateProp,
  FaSymbol,
} from "@fortawesome/fontawesome-svg-core";
declare export function FontAwesomeIcon(
  props: FontAwesomeIconProps
): React$Node;

/**
 * @deprecated use FontAwesomeIconProps
 */
export type Props = FontAwesomeIconProps;
declare type BackwardCompatibleOmit<T, K: $Keys<any>> = Pick<
  T,
  Exclude<$Keys<T>, K>
>;
export type FontAwesomeIconProps = {
  icon: IconProp,
  mask?: IconProp,
  className?: string,
  color?: string,
  spin?: boolean,
  pulse?: boolean,
  border?: boolean,
  fixedWidth?: boolean,
  inverse?: boolean,
  listItem?: boolean,
  flip?: FlipProp,
  size?: SizeProp,
  pull?: PullProp,
  rotation?: RotateProp,
  transform?: string | Transform,
  symbol?: FaSymbol,
  style?: CSSProperties,
  tabIndex?: number,
  title?: string,
  swapOpacity?: boolean,
  ...
} & BackwardCompatibleOmit<DOMAttributes<SVGSVGElement>, "children" | "mask">;
